#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, HistoryPolicy, ReliabilityPolicy, DurabilityPolicy
import sys
import open3d
from industrial_reconstruction_msgs.srv import StartReconstruction
from industrial_reconstruction_msgs.srv import StopReconstruction
from industrial_reconstruction.industrial_reconstruction import meshToRos
from visualization_msgs.msg import Marker
import shutil
import os
import numpy as np

MESH_FILE_PARAMETER = "mesh_file"
REFERENCE_FRAME_PARAMETER = "reference_frame"
TSDF_MIN_X_PARAMETER = "ir_min_x"
TSDF_MIN_Y_PARAMETER = "ir_min_y"
TSDF_MIN_Z_PARAMETER = "ir_min_z"
TSDF_MAX_X_PARAMETER = "ir_max_x"
TSDF_MAX_Y_PARAMETER = "ir_max_y"
TSDF_MAX_Z_PARAMETER = "ir_max_z"
MESH_TOPIC = "mesh"
TSDF_VOLUME_TOPIC = "tsdf_volume"


class ReconstructionSimServer(Node):
    def __init__(self):
        super().__init__("reconstruction_sim_node")

        self.start_srv = self.create_service(StartReconstruction, "start_reconstruction", self.start_cb)
        self.stop_srv = self.create_service(StopReconstruction, "stop_reconstruction", self.stop_cb)

        topic_qos = QoSProfile(
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
            history=HistoryPolicy.KEEP_LAST,
            depth=1
        )

        self.scan_mesh_pub = self.create_publisher(Marker, MESH_TOPIC, topic_qos)
        self.tsdf_volume_pub = self.create_publisher(Marker, TSDF_VOLUME_TOPIC, topic_qos)

        self.declare_parameter(MESH_FILE_PARAMETER, rclpy.Parameter.Type.STRING)
        self.declare_parameter(REFERENCE_FRAME_PARAMETER, rclpy.Parameter.Type.STRING)
        self.declare_parameter(TSDF_MIN_X_PARAMETER, rclpy.Parameter.Type.DOUBLE)
        self.declare_parameter(TSDF_MIN_Y_PARAMETER, rclpy.Parameter.Type.DOUBLE)
        self.declare_parameter(TSDF_MIN_Z_PARAMETER, rclpy.Parameter.Type.DOUBLE)
        self.declare_parameter(TSDF_MAX_X_PARAMETER, rclpy.Parameter.Type.DOUBLE)
        self.declare_parameter(TSDF_MAX_Y_PARAMETER, rclpy.Parameter.Type.DOUBLE)
        self.declare_parameter(TSDF_MAX_Z_PARAMETER, rclpy.Parameter.Type.DOUBLE)

        self.get_logger().info("Started simulated reconstruction node")

    def start_cb(self, _request, response):
        # Publish the simulated TSDF volume
        min_bound = np.asarray([self.get_parameter(TSDF_MIN_X_PARAMETER).value,
                                self.get_parameter(TSDF_MIN_Y_PARAMETER).value,
                                self.get_parameter(TSDF_MIN_Z_PARAMETER).value])
        max_bound = np.asarray([self.get_parameter(TSDF_MAX_X_PARAMETER).value,
                                self.get_parameter(TSDF_MAX_Y_PARAMETER).value,
                                self.get_parameter(TSDF_MAX_Z_PARAMETER).value])

        crop_box_msg = Marker()
        crop_box_msg.type = crop_box_msg.CUBE
        crop_box_msg.action = crop_box_msg.ADD
        crop_box_msg.id = 1
        crop_box_msg.frame_locked = True
        crop_box_msg.scale.x = max_bound[0] - min_bound[0]
        crop_box_msg.scale.y = max_bound[1] - min_bound[1]
        crop_box_msg.scale.z = max_bound[2] - min_bound[2]
        crop_box_msg.pose.position.x = (min_bound[0] + max_bound[0]) / 2.0
        crop_box_msg.pose.position.y = (min_bound[1] + max_bound[1]) / 2.0
        crop_box_msg.pose.position.z = (min_bound[2] + max_bound[2]) / 2.0
        crop_box_msg.pose.orientation.w = 1.0
        crop_box_msg.pose.orientation.x = 0.0
        crop_box_msg.pose.orientation.y = 0.0
        crop_box_msg.pose.orientation.z = 0.0
        crop_box_msg.color.r = 1.0
        crop_box_msg.color.g = 0.0
        crop_box_msg.color.b = 0.0
        crop_box_msg.color.a = 0.25
        crop_box_msg.header.frame_id = self.get_parameter(REFERENCE_FRAME_PARAMETER).value
        self.tsdf_volume_pub.publish(crop_box_msg)

        response.success = True
        return response

    def stop_cb(self, request, response):
        try:
            # Copy the mesh to the target destination
            mesh_file = self.get_parameter(MESH_FILE_PARAMETER).value
            os.makedirs(os.path.dirname(mesh_file), exist_ok=True)
            shutil.copy2(mesh_file, request.mesh_filepath)

            # Publish the mesh visualization message
            msg = meshToRos(open3d.io.read_triangle_mesh(mesh_file))
            msg.frame_locked = True
            msg.header.frame_id = self.get_parameter(REFERENCE_FRAME_PARAMETER).value
            self.scan_mesh_pub.publish(msg)

            response.success = True
            response.message = f'Scanning simulation complete; mesh saved to "{mesh_file}"'

        except Exception as e:
            response.success = False
            response.message = str(e)

        return response


def main():
    rclpy.init(args=sys.argv)
    node = ReconstructionSimServer()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == '__main__':
    main()
