#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from snp_msgs.srv import GenerateScanMotionPlan
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
import yaml
from builtin_interfaces.msg import Duration, Time
from std_msgs.msg import Header


class ScanMotionPlanFromFileNode(Node):

    def __init__(self):
        super().__init__('scan_traj_service')
        self.srv = self.create_service(GenerateScanMotionPlan, 'generate_scan_motion_plan',
                                       self.callback)
        self.scan_trajectory_file_path = self.declare_parameter("scan_trajectory_file", rclpy.Parameter.Type.STRING).value

    def callback(self, request, response):
        with open(self.scan_trajectory_file_path, "r") as file_input:
            try:
                scan_traj = yaml.safe_load(file_input)
            except yaml.YAMLError as exc:
                self.get_logger().info(str(exc))
        header = response.motion_plan.header
        header.stamp = Time(sec=int(scan_traj['header']['stamp']['sec']),nanosec=int(scan_traj['header']['stamp']['nanosec']))
        header.frame_id = scan_traj['header']['frame_id']
        response.motion_plan.joint_names = scan_traj['joint_names']
        for point_val in scan_traj['points']:
            point = JointTrajectoryPoint()
            point.positions = point_val['positions']
            point.velocities = point_val['velocities']
            point.accelerations = point_val['accelerations']
            point.effort = point_val['effort']
            point.time_from_start = Duration(sec = int(point_val['time_from_start']['sec']),
                                             nanosec= int(point_val['time_from_start']['nanosec']))
            response.motion_plan.points.append(point)
        return response


def main(args=None):
    rclpy.init(args=args)
    node = ScanMotionPlanFromFileNode()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == '__main__':
    main()
