# Anchors

foo: &raw_inputs
  program: input_data
  environment: environment
  profiles: profiles
bar: &mod_inputs
  program: output_data
  environment: environment
  profiles: profiles

DoneTask: &done
  class: DoneTaskFactory
  config:
    conditional: false
ErrorTask: &error
  class: ErrorTaskFactory
  config:
    conditional: false
    trigger_abort: true
MinLengthTask: &min_length
  class: MinLengthTaskFactory
  config:
    conditional: true
    inputs: *raw_inputs
    outputs:
      program: output_data
    format_result_as_input: false
TrajOptMotionPlannerTask: &trajopt
  class: TrajOptMotionPlannerTaskFactory
  config:
    conditional: true
    inputs: *mod_inputs
    outputs:
      program: output_data
    format_result_as_input: false
DiscreteContactCheckTask: &contact_check
  class: DiscreteContactCheckTaskFactory
  config:
    conditional: true
    inputs: *mod_inputs
ConstantTCPSpeedTimeParameterizationTask: &constant_tcp_speed
  class: ConstantTCPSpeedTimeParameterizationTaskFactory
  config:
    conditional: true
    inputs: *mod_inputs
    outputs:
      program: output_data
IterativeSplineParameterizationTask: &isp
  class: IterativeSplineParameterizationTaskFactory
  config:
    conditional: true
    inputs: *mod_inputs
    outputs:
      program: output_data
KinematicLimitsCheckTask: &limits_check
  class: KinematicLimitsCheckTaskFactory
  config:
    conditional: true
    inputs: *mod_inputs

# Task composer configuration
task_composer_plugins:
  search_libraries:
    - snp_motion_planning_tasks
  executors:
    default: TaskflowExecutor
    plugins:
      TaskflowExecutor:
        class: TaskflowTaskComposerExecutorFactory
        config:
          threads: 8
  tasks:
    plugins:    
      SNPCartesianPipeline:
        class: GraphTaskFactory
        config:
          inputs:
            program: input_data
          outputs:
            program: output_data
          nodes:
            DoneTask: *done
            ErrorTask: *error
            MinLengthTask: *min_length
            TrajOptMotionPlannerTask: *trajopt
            DiscreteContactCheckTask: *contact_check
            ConstantTCPSpeedTimeParameterizationTask: *constant_tcp_speed
            KinematicLimitsCheckTask: *limits_check
          edges:
            - source: MinLengthTask
              destinations: [ErrorTask, TrajOptMotionPlannerTask]
            - source: TrajOptMotionPlannerTask
              destinations: [ErrorTask, DiscreteContactCheckTask]
            - source: DiscreteContactCheckTask
              destinations: [ErrorTask, ConstantTCPSpeedTimeParameterizationTask]
            - source: ConstantTCPSpeedTimeParameterizationTask
              destinations: [ErrorTask, KinematicLimitsCheckTask]
            - source: KinematicLimitsCheckTask
              destinations: [ErrorTask, DoneTask]
          terminals: [ErrorTask, DoneTask]
      SNPFreespacePipeline:
        class: GraphTaskFactory
        config:
          inputs:
            program: input_data
          outputs:
            program: output_data
          nodes:
            DoneTask: *done
            ErrorTask: *error
            MinLengthTask: *min_length
            OMPLMotionPlannerTask:
              class: OMPLMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: *mod_inputs
                outputs:
                  program: output_data
                format_result_as_input: true
            TrajOptMotionPlannerTask: *trajopt
            DiscreteContactCheckTask: *contact_check
            IterativeSplineParameterizationTask: *isp
            KinematicLimitsCheckTask: *limits_check
          edges:
            - source: MinLengthTask
              destinations: [ErrorTask, OMPLMotionPlannerTask]
            - source: OMPLMotionPlannerTask
              destinations: [ErrorTask, TrajOptMotionPlannerTask]
            - source: TrajOptMotionPlannerTask
              destinations: [ErrorTask, DiscreteContactCheckTask]
            - source: DiscreteContactCheckTask
              destinations: [ErrorTask, IterativeSplineParameterizationTask]
            - source: IterativeSplineParameterizationTask
              destinations: [ErrorTask, KinematicLimitsCheckTask]
            - source: KinematicLimitsCheckTask
              destinations: [ErrorTask, DoneTask]
          terminals: [ErrorTask, DoneTask]
      SNPTransitionPipeline:
        class: GraphTaskFactory
        config:
          inputs:
            program: input_data
          outputs:
            program: output_data
          nodes:
            DoneTask: *done
            ErrorTask: *error
            MinLengthTask: *min_length
            TrajOptMotionPlannerTask: *trajopt
            OMPLMotionPlannerTask:
              class: OMPLMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: *mod_inputs
                outputs:
                  program: output_data
                format_result_as_input: false
            DiscreteContactCheckTask: *contact_check
            IterativeSplineParameterizationTask: *isp
            KinematicLimitsCheckTask: *limits_check
          edges:
            - source: MinLengthTask
              destinations: [ErrorTask, TrajOptMotionPlannerTask]
            - source: TrajOptMotionPlannerTask
              destinations: [OMPLMotionPlannerTask, DiscreteContactCheckTask]
            - source: OMPLMotionPlannerTask
              destinations: [ErrorTask, DiscreteContactCheckTask]
            - source: DiscreteContactCheckTask
              destinations: [ErrorTask, IterativeSplineParameterizationTask]
            - source: IterativeSplineParameterizationTask
              destinations: [ErrorTask, KinematicLimitsCheckTask]
            - source: KinematicLimitsCheckTask
              destinations: [ErrorTask, DoneTask]
          terminals: [ErrorTask, DoneTask]
      SNPPipeline:
        class: GraphTaskFactory
        config:
          inputs:
            program: input_data
          outputs:
            program: output_data
          nodes:
            DoneTask: *done
            ErrorTask: *error
            SimpleMotionPlannerTask:
              class: SimpleMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: *raw_inputs
                outputs:
                  program: output_data
                format_result_as_input: true
            DescartesMotionPlannerTask:
              class: DescartesFMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: *mod_inputs
                outputs:
                  program: output_data
                format_result_as_input: true
            RasterMotionTask:
              class: RasterMotionTaskFactory
              config:
                conditional: true
                inputs:
                  program: output_data
                  environment: environment
                outputs:
                  program: output_data
                freespace:
                  task: SNPFreespacePipeline
                  config:
                    remapping:
                      input_data: output_data
                      output_data: output_data
                    indexing: [output_data]
                raster:
                  task: SNPCartesianPipeline
                  config:
                    remapping:
                      input_data: output_data
                      output_data: output_data
                    indexing: [output_data]
                transition:
                  task: SNPTransitionPipeline
                  config:
                    remapping:
                      input_data: output_data
                      output_data: output_data
                    indexing: [output_data]
            TCPSpeedLimiterTask:
              class: TCPSpeedLimiterTaskFactory
              config:
                conditional: true
                inputs: *mod_inputs
                outputs:
                  program: output_data
          edges:
            - source: SimpleMotionPlannerTask
              destinations: [ErrorTask, DescartesMotionPlannerTask]
            - source: DescartesMotionPlannerTask
              destinations: [ErrorTask, RasterMotionTask]
            - source: RasterMotionTask
              destinations: [ErrorTask, TCPSpeedLimiterTask]
            - source: TCPSpeedLimiterTask
              destinations: [ErrorTask, DoneTask]
          terminals: [ErrorTask, DoneTask]
