# Request

# Params
string motion_group
string tcp_frame
sensor_msgs/JointState js1
sensor_msgs/JointState js2

---
# Response

# Motion Plan - a joint trajectory for the robot to follow
trajectory_msgs/JointTrajectory trajectory

# Success and error information
bool success
string message
