# Request
sensor_msgs/JointState js1
sensor_msgs/JointState js2
string motion_group

---
# Response

# Motion Plan - a joint trajectory for the robot to follow
trajectory_msgs/JointTrajectory trajectory

# Success and error information
bool success
string message
